Add readme with example of utilisation and installation
anthropedia/tci-i18n pull request #4
Opened 2017-05-15 12:28 UTC by Ydrasil

2017-05-15 12:29 UTC, Ydrasil commented
@vinyll

2017-05-15 12:57 UTC, vinyll requested changes

2017-05-15 12:57 UTC, vinyll commented on readme.md
> +Tci-i18n provide translation from CSV translation files.
from CSV ~translation~ files.

2017-05-15 12:57 UTC, vinyll commented on readme.md
> +CSV files can have this format
> … and should be UTF-8 encoded

2017-05-15 12:57 UTC, vinyll commented on readme.md
> +python3 -m venv venv
We don't need any virtualenv here as there's no specific installation

2017-05-15 12:57 UTC, vinyll commented on readme.md
> +source venv/bin/activate
Same for tests

2017-05-15 15:22 UTC, Ydrasil commented
@vinyll

2017-05-26 08:14 UTC, vinyll requested changes

2017-05-26 08:14 UTC, vinyll commented on readme.md
> +Tci-i18n provide translation from CSV files.
TCI-i18n _provides_

2017-05-26 08:14 UTC, vinyll commented on readme.md
> +CSV files can have this format and and should be UTF-8 encoded
missing the final point "."

2017-05-26 08:14 UTC, vinyll commented on readme.md
> +### Utilisation
`## Usage`

2017-06-02 14:43 UTC, vinyll approved these changes

2017-06-02 14:43 UTC, merged